services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: cadastro-lotes-pom:latest
    container_name: cadastro-lotes-pom
    env_file:
      - .env
    environment:
      - APP_HEADLESS=true
    volumes:
      # Persistência dos logs no host
      - ./logs:/app/logs
      - ./evidencias:/app/evidencias
    restart: "no"
